export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  GET_TO_CART_REQUEST: "GET_TO_CART_REQUEST",
  GET_TO_CART_SUCCESS: "GET_TO_CART_SUCCESS",
  GET_TO_CART_FAILURE: "GET_TO_CART_FAILURE",
  REMOVE_FROM_CART_REQUEST: "REMOVE_FROM_CART_REQUEST",
  REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
  REMOVE_FROM_CART_FAILURE: "REMOVE_FROM_CART_FAILURE",
};
// export const categoryConstants = {
//     GET_ALL_CATEGORY_REQUEST:'GET_ALL_CATEGORY_REQUEST',
//     GET_ALL_CATEGORY_SUCCESS:'GET_ALL_CATEGORY_SUCCESS',
//     GET_ALL_CATEGORY_FAILURE:'GET_ALL_CATEGORY_FAILURE',
//     ADD_NEW_CATEGORY_REQUEST:'ADD_NEW_CATEGORY_REQUEST',
//     ADD_NEW_CATEGORY_SUCCESS:'ADD_NEW_CATEGORY_SUCCESS',
//     ADD_NEW_CATEGORY_FAILURE:'ADD_NEW_CATEGORY_FAILURE',
//     UPDATE_CATEGORY_REQUEST:'UPDATE_CATEGORY_REQUEST',
//     UPDATE_CATEGORY_SUCCESS:'UPDATE_CATEGORY_SUCCESS',
//     UPDATE_CATEGORY_FAILURE:'UPDATE_CATEGORY_FAILURE',
//     DELETE_CATEGORY_REQUEST:'DELETE_CATEGORY_REQUEST',
//     DELETE_CATEGORY_SUCCESS:'DELETE_CATEGORY_SUCCESS',
//     DELETE_CATEGORY_FAILURE:'DELETE_CATEGORY_FAILURE'
// }

export const moviesConstants = {
  GET_ALL_MOVIE_REQUEST: "GET_ALL_MOVIE_REQUEST",
  GET_ALL_MOVIE_SUCCESS: "GET_ALL_MOVIE_SUCCESS",
  GET_ALL_MOVIE_FAILURE: "GET_ALL_MOVIE_FAILURE",
};

export const movieConstants = {
  GET_MOVIE_REQUEST: "GET_MOVIE_REQUEST",
  GET_MOVIE_SUCCESS: "GET_MOVIE_SUCCESS",
  GET_MOVIE_FAILURE: "GET_MOVIE_FAILURE",
};

export const theaterConstants = {
  GET_ALL_THEATER_REQUEST: "GET_ALL_THEATER_REQUEST",
  GET_ALL_THEATER_SUCCESS: "GET_ALL_THEATER_SUCCESS",
  GET_ALL_THEATER_FAILURE: "GET_ALL_THEATER_FAILURE",
  ADD_THEATER_REQUEST: "ADD_THEATER_REQUEST",
  ADD_THEATER_SUCCESS: "ADD_THEATER_SUCCESS",
  ADD_THEATER_FAILURE: "ADD_THEATER_FAILURE",
};

// export const initialDataConstants = {
//     GET_ALL_initialData_REQUEST:'GET_ALL_initialData_REQUEST',
//     GET_ALL_initialData_SUCCESS:'GET_ALL_initialData_SUCCESS',
//     GET_ALL_initialData_FAILURE:'GET_ALL_initialData_FAILURE'
// }

// export const pageConstants = {
//     CREATE_PAGE_REQUEST:'CREATE_PAGE_REQUEST',
//     CREATE_PAGE_SUCCESS:'CREATE_PAGE_SUCCESS',
//     CREATE_PAGE_FAILURE:'CREATE_PAGE_FAILURE'
// };
